version: "3"

services:
  web:
    build: .
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - HTTP_PORT
      - BOOT_LOCAL_REPO=/usr/src/app/.m2

  repl:
    build: .
    command: boot repl -b ${REPL_HOST} -p ${REPL_PORT}
    volumes:
        - .:/usr/src/app
    ports:
      - "${REPL_PORT}:${REPL_PORT}"
      - "${HTTP_PORT}:${HTTP_PORT}"
    environment:
      - HTTP_PORT=3500
      - BOOT_LOCAL_REPO=/usr/src/app/.m2

  test:
    build: .
    command: boot test
    volumes:
        - .:/usr/src/app
    environment:
      - HTTP_PORT
      - BOOT_LOCAL_REPO=/usr/src/app/.m2
